# Generated by Django 3.2.16 on 2022-12-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('museums', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuseumEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок события')),
                ('slug', models.SlugField(max_length=100, verbose_name='уникальный слаг(путь) события')),
                ('date', models.DateField(verbose_name='дата события')),
                ('description', models.TextField(verbose_name='описание события')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='museums.museum', verbose_name='музей, в котором происходит это событие')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
            },
        ),
    ]
