# Generated by Django 3.2.16 on 2022-12-24 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0010_auto_20221224_1413'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='museumevent',
            options={'verbose_name': 'событие', 'verbose_name_plural': 'события'},
        ),
        migrations.AlterField(
            model_name='museumevent',
            name='date',
            field=models.DateField(verbose_name='дата события'),
        ),
        migrations.AlterField(
            model_name='museumevent',
            name='description',
            field=models.TextField(verbose_name='описание события'),
        ),
        migrations.AlterField(
            model_name='museumevent',
            name='museum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='museums.museum', verbose_name='музей, в котором происходит это событие'),
        ),
        migrations.AlterField(
            model_name='museumevent',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='уникальный слаг(путь) события'),
        ),
        migrations.AlterField(
            model_name='museumevent',
            name='title',
            field=models.CharField(max_length=150, verbose_name='заголовок события'),
        ),
    ]
