# Generated by Django 3.2.16 on 2022-12-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('museums', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название обьекта')),
                ('slug', models.SlugField(max_length=100, verbose_name='уникальный слаг(путь) для обьекта')),
                ('description', models.TextField(verbose_name='описание обьекта')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m', verbose_name='изображение обьекта')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='museums.museum', verbose_name='музей, к которому принадлежит этот экспонат')),
            ],
            options={
                'verbose_name': 'экспонат',
                'verbose_name_plural': 'экспонаты',
            },
        ),
    ]
