# Generated by Django 3.2.16 on 2022-12-24 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0010_auto_20221224_1413'),
        ('exhibits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibit',
            options={'verbose_name': 'экспонат', 'verbose_name_plural': 'экспонаты'},
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='description',
            field=models.TextField(verbose_name='описание обьекта'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='image',
            field=models.ImageField(default='static/noimage.png', upload_to='uploads/%Y/%m', verbose_name='изображение обьекта'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='museum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='museums.museum', verbose_name='музей, к которому принадлежит этот экспонат'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название обьекта'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='уникальный слаг(путь) для обьекта'),
        ),
    ]
