# Generated by Django 3.2.16 on 2022-12-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=168, verbose_name='название города')),
                ('slug', models.CharField(max_length=150, verbose_name='уникальный слаг(путь) города')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название обьекта')),
                ('slug', models.SlugField(max_length=100, verbose_name='уникальный слаг(путь) для обьекта')),
                ('description', models.TextField(verbose_name='описание обьекта')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m', verbose_name='изображение обьекта')),
                ('address', models.TextField(blank=True, verbose_name='адрес музея')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='museums', to='museums.city', verbose_name='город, в котором расположен текущий музей')),
            ],
            options={
                'verbose_name': 'музей',
                'verbose_name_plural': 'музеи',
            },
        ),
    ]
