# Generated by Django 3.2.16 on 2022-12-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("museums", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Exhibit",
        ),
    ]
