# Generated by Django 3.2.16 on 2022-12-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0002_delete_exhibit'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='city',
            field=models.CharField(blank=True, max_length=168),
        ),
        migrations.AddField(
            model_name='museum',
            name='link',
            field=models.TextField(default='У данного музея нет собственного сайта'),
        ),
    ]
