# Generated by Django 3.2.16 on 2022-12-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museums", "0003_auto_20221216_2130"),
    ]

    operations = [
        migrations.AddField(
            model_name="museum",
            name="link",
            field=models.TextField(default="У данного музея нет собственного сайта"),
        ),
    ]
