# Generated by Django 3.2.16 on 2022-12-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museums", "0004_museum_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="museum",
            name="city",
            field=models.CharField(max_length=168),
        ),
    ]
