# Generated by Django 3.2.16 on 2022-12-24 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0009_delete_museumevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'город', 'verbose_name_plural': 'города'},
        ),
        migrations.AlterModelOptions(
            name='museum',
            options={'verbose_name': 'музей', 'verbose_name_plural': 'музеи'},
        ),
        migrations.RemoveField(
            model_name='museum',
            name='link',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=168, verbose_name='название города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(max_length=150, verbose_name='уникальный слаг(путь) города'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='address',
            field=models.TextField(blank=True, verbose_name='адрес музея'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='museums', to='museums.city', verbose_name='город, в котором расположен текущий музей'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='description',
            field=models.TextField(verbose_name='описание обьекта'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='image',
            field=models.ImageField(default='static/noimage.png', upload_to='uploads/%Y/%m', verbose_name='изображение обьекта'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название обьекта'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='уникальный слаг(путь) для обьекта'),
        ),
    ]
