# Generated by Django 3.2.16 on 2022-12-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HPEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("link", models.TextField(blank=True)),
                ("city", models.CharField(max_length=168)),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
                "abstract": False,
            },
        ),
    ]
