# Generated by Django 3.2.16 on 2022-12-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_hpevent_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HPEvent',
        ),
    ]
